### PR TITLE
Updated 6.7.z nailgun branch

### PR DESCRIPTION
**Pull request by devendra104**

### CODE REVIEW

**Comment by vijay8451** [comment]
Travis failed
```
  Cloning https://github.com/SatelliteQE/nailgun.git (to revision 6.7.z) to /tmp/pip-install-zlvhrgbg/nailgun

  Did not find branch or tag '6.7.z', assuming revision or ref.

error: pathspec '6.7.z' did not match any file(s) known to git

Command "git checkout -q 6.7.z" failed with error code 1 in /tmp/pip-install-zlvhrgbg/nailgun

The command "pip install -r requirements.txt" failed and exited with 1 during .
```

**Comment by devendra104** [comment]
> Travis failed
> 
> ```
>   Cloning https://github.com/SatelliteQE/nailgun.git (to revision 6.7.z) to /tmp/pip-install-zlvhrgbg/nailgun
> 
>   Did not find branch or tag '6.7.z', assuming revision or ref.
> 
> error: pathspec '6.7.z' did not match any file(s) known to git
> 
> Command "git checkout -q 6.7.z" failed with error code 1 in /tmp/pip-install-zlvhrgbg/nailgun
> 
> The command "pip install -r requirements.txt" failed and exited with 1 during .
> ```
Because nailgun 6.7.z branch has not been created yet, Once it will be done, We will not see this failure.

**Comment by mirekdlugosz** [comment]
Nailgun 6.7.z branch was created today, I have re-run Travis and it passed.

**Comment by devendra104** [comment]
> Nailgun 6.7.z branch was created today, I have re-run Travis and it passed.

Thanks Mirek.

**Pull request merged**
