### PR TITLE
Added create_capsule_ak fab function

### PR DESCRIPTION
**Pull request by vsedmik**
Added create_capsule_ak fab function for AK creation on a blank Satellite.

### CODE REVIEW

**Comment by vsedmik** [comment]
**Test result:**

1) Satellite 6.9.3, DISTRIBUTION="cdn":
```
# hammer activation-key product-content --organization-id 1 --name rhel7_capsule_ak
-----|-------------------------------------------------------------------------|--------------------------------------------|------------------|----------
ID   | NAME                                                                    | LABEL                                      | DEFAULT ENABLED? | OVERRIDE 
-----|-------------------------------------------------------------------------|--------------------------------------------|------------------|----------
5683 | Red Hat Ansible Engine 2.9 RPMs for Red Hat Enterprise Linux 7 Server   | rhel-7-server-ansible-2.9-rpms             | no               | enabled:1
2682 | Red Hat Enterprise Linux 7 Server (RPMs)                                | rhel-7-server-rpms                         | yes              |          
1615 | Red Hat Satellite Capsule 6.9 (for RHEL 7 Server) (RPMs)                | rhel-7-server-satellite-capsule-6.9-rpms   | no               | enabled:1
2759 | Red Hat Satellite Maintenance 6 (for RHEL 7 Server) (RPMs)              | rhel-7-server-satellite-maintenance-6-rpms | no               | enabled:1
2660 | Red Hat Satellite Tools 6.9 (for RHEL 7 Server) (RPMs)                  | rhel-7-server-satellite-tools-6.9-rpms     | no               | enabled:1
6345 | Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server | rhel-server-rhscl-7-rpms                   | no               | enabled:1
-----|-------------------------------------------------------------------------|--------------------------------------------|------------------|----------
```

2) Satellite 6.10.0, DISTRIBUTION="downstream":
```
# hammer activation-key product-content --organization-id 1 --name rhel7_capsule_ak
-----|-------------------------------------------------------------------------|-------------------------------------------------------------|------------------|----------
ID   | NAME                                                                    | LABEL                                                       | DEFAULT ENABLED? | OVERRIDE 
-----|-------------------------------------------------------------------------|-------------------------------------------------------------|------------------|----------
7054 | capsule6_latest_repo                                                    | Default_Organization_capsule6_latest_capsule6_latest_repo   | yes              |          
7056 | capsuletools_repo                                                       | Default_Organization_capsuletools_product_capsuletools_repo | yes              |          
7055 | maintenance_repo                                                        | Default_Organization_maintenance_latest_7_maintenance_repo  | yes              |          
5545 | Red Hat Ansible Engine 2.9 RPMs for Red Hat Enterprise Linux 7 Server   | rhel-7-server-ansible-2.9-rpms                              | no               | enabled:1
2547 | Red Hat Enterprise Linux 7 Server (RPMs)                                | rhel-7-server-rpms                                          | yes              |          
6181 | Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server | rhel-server-rhscl-7-rpms                                    | no               | enabled:1
-----|-------------------------------------------------------------------------|-------------------------------------------------------------|------------------|----------
```

**Comment by devendra104** [comment]
@vsedmik Could you please rebase your changes?

**Comment by vsedmik** [comment]
Rebased @devendra104

**Review by devendra104 — APPROVED** [review]
ACK

**Pull request merged**
