### PR TITLE
RHEVM4 Improvement

### PR DESCRIPTION
**Pull request by jyejare**
The PR contains:
1. The new rhev4 module
2. The test_helpers  and the upgrade_helpers functions are updated for rhev4
3. Requirements changed to rhev4 as default

### CODE REVIEW

**Comment by jyejare** [comment]
Fixes #187

**Comment by sghai** [comment]
have we tested this change ? if so, do you see any issue ?

**Comment by jyejare** [comment]
@sghai , Yeah It works very well and no issues at all -

RHEVm4 Fab Tasks Stdouts:

```
# fab -u root delete_rhevm4_instance:'upgrade_satellite_auto_rhel6'
Deleting instance upgrade_satellite_auto_rhel6 from RHEVM.
INFO:upgrade_logging:Deleting instance upgrade_satellite_auto_rhel6 from RHEVM.
Current Status: POWERING_DOWN
INFO:upgrade_logging:Current Status: POWERING_DOWN
Current Status: POWERING_DOWN
INFO:upgrade_logging:Current Status: POWERING_DOWN
Current Status: POWERING_DOWN
INFO:upgrade_logging:Current Status: POWERING_DOWN
Current Status: POWERING_DOWN
INFO:upgrade_logging:Current Status: POWERING_DOWN
Current Status: POWERING_DOWN
INFO:upgrade_logging:Current Status: POWERING_DOWN
Current Status: POWERING_DOWN
INFO:upgrade_logging:Current Status: POWERING_DOWN
Current Status: POWERING_DOWN
INFO:upgrade_logging:Current Status: POWERING_DOWN
Current Status: POWERING_DOWN
INFO:upgrade_logging:Current Status: POWERING_DOWN
Current Status: POWERING_DOWN
INFO:upgrade_logging:Current Status: POWERING_DOWN
Current Status: POWERING_DOWN
INFO:upgrade_logging:Current Status: POWERING_DOWN
Current Status: POWERING_DOWN
INFO:upgrade_logging:Current Status: POWERING_DOWN
Current Status: POWERING_DOWN
INFO:upgrade_logging:Current Status: POWERING_DOWN
Current Status: POWERING_DOWN
INFO:upgrade_logging:Current Status: POWERING_DOWN
Current Status: POWERING_DOWN
INFO:upgrade_logging:Current Status: POWERING_DOWN
Current Status: DOWN
INFO:upgrade_logging:Current Status: DOWN
Instance upgrade_satellite_auto_rhel6 is now deleted from RHEVM!
INFO:upgrade_logging:Instance upgrade_satellite_auto_rhel6 is now deleted from RHEVM!

Done.
```

```
# fab -u root create_rhevm4_instance:'upgrade_satellite_auto_rhel6','qe-sat6-upgrade-rhel6-sat62'
Turning on instance upgrade_satellite_auto_rhel6 from template qe-sat6-upgrade-rhel6-sat62. Please wait till get up ...
INFO:upgrade_logging:Turning on instance upgrade_satellite_auto_rhel6 from template qe-sat6-upgrade-rhel6-sat62. Please wait till get up ...
Current Status: IMAGE_LOCKED
INFO:upgrade_logging:Current Status: IMAGE_LOCKED
Current Status: DOWN
INFO:upgrade_logging:Current Status: DOWN
Current Status: POWERING_UP
INFO:upgrade_logging:Current Status: POWERING_UP
Current Status: POWERING_UP
INFO:upgrade_logging:Current Status: POWERING_UP
Current Status: POWERING_UP
INFO:upgrade_logging:Current Status: POWERING_UP
Current Status: POWERING_UP
INFO:upgrade_logging:Current Status: POWERING_UP
Current Status: POWERING_UP
INFO:upgrade_logging:Current Status: POWERING_UP
Current Status: POWERING_UP
INFO:upgrade_logging:Current Status: POWERING_UP
Current Status: POWERING_UP
INFO:upgrade_logging:Current Status: POWERING_UP
Current Status: POWERING_UP
INFO:upgrade_logging:Current Status: POWERING_UP
Current Status: POWERING_UP
INFO:upgrade_logging:Current Status: POWERING_UP
Current Status: UP
INFO:upgrade_logging:Current Status: UP
Instance upgrade_satellite_auto_rhel6 is now up !
INFO:upgrade_logging:Instance upgrade_satellite_auto_rhel6 is now up !

Done.
```

**Comment by sghai** [comment]
Cool.. you have my ACK then based on above results.

**Pull request merged**
