### PR TITLE
Make packages updated verbose

### PR DESCRIPTION
**Pull request by ntkathole**
The problem is we are not able to see which packages updated during upgrade in console.

### CODE REVIEW

**Comment by jyejare** [comment]
I think there was a reason why we disabled it. Maybe longer output of yum update is one of the reasons for it.

Can we redirect the output of yum update to a file instead?

**Comment by ntkathole** [comment]
> I think there was a reason why we disabled it. Maybe longer output of yum update is one of the reasons for it.
> 
> Can we redirect the output of yum update to a file instead?

I think its ok if output goes long. It is important to have which packages updated and helps to look easily if something come up.

**Comment by jyejare** [comment]
> > I think there was a reason why we disabled it. Maybe longer output of yum update is one of the reasons for it.
> > Can we redirect the output of yum update to a file instead?
> 
> I think its ok if output goes long. It is important to have which packages updated and helps to look easily if something come up. Even f-m also prints complete output so it might not be the problem.

Yeah of-course its important, I am not opposing to have the package update data. But stdout on jenknins actually throws tons of lines while running yum update which u even cant catch them all and its really annoying.

Redirecting will help as u can go and tail -f the file which will be more easier.

@sghai  Any thoughts here ?

**Comment by san7ket** [comment]
Moving to pipelines would solve this, as it would be a separate steps. but I feel we shouldn't drop files, when we can have it on console.
If we are facing issue with longer logs or extracting relevant data from log. We can give https://wiki.jenkins.io/display/JENKINS/Log+Parser+Plugin , It's already part of our env, but someone has to set the rules and activates it.

Also, I don't agree on adding quiet while testing our product.

**Comment by ntkathole** [comment]
We have foreman-maintain target version available now and it prints packages updated on console. Closing this as f-m fulfil the purpose of what I need.

**Pull request closed without merging**
